scan_timeout = 50

[aws]
disabled = true

[gcloud]
disabled = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[c]
format = "via [$symbol]($style)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = " "

[hostname]
disabled = true

# language
[docker_context]
disabled = true

[golang]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true
